# Generated by Django 4.2.6 on 2023-11-03 15:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=blog.models.default_image, upload_to='article_images/'),
        ),
    ]
